%% ============================================================
% z0Sensitivity_OracleReferencedAngle_Plot.m
%
% Purpose
% -------
% This script generates all figures for the pseudo-label initialization
% sensitivity analysis based on the oracle-referenced canonical-angle
% summaries.
%
% Input
% -----
%   Results/
%       FWCCA_z0Sensitivity_oracleReferenced_angle_summary_all.mat
%
% Output
% ------
% All figures generated by this script are saved in:
%
%   Figures/
%
% Main manuscript:
%
%   Figure 10:
%   Mean canonical angles relative to the oracle first direction under
%   different pseudo-label initializations:
%   (a) G-FWCCA, (b) LG-FWCCA, and (c) GL-FWCCA.
%
% Supplementary Materials:
%
%   Figure 14:
%   Mean canonical angles relative to the oracle second direction under
%   different pseudo-label initializations:
%   (a) G-FWCCA, (b) LG-FWCCA, and (c) GL-FWCCA.
%
%   Figure 15:
%   95th-percentile canonical angles relative to the oracle first
%   direction under different pseudo-label initializations:
%   (a) G-FWCCA, (b) LG-FWCCA, and (c) GL-FWCCA.
%
%   Figure 16:
%   95th-percentile canonical angles relative to the oracle second
%   direction under different pseudo-label initializations:
%   (a) G-FWCCA, (b) LG-FWCCA, and (c) GL-FWCCA.
%
%% ============================================================

clear; clc; close all;


%% ============================================================
% Project directories
%% ============================================================

% Directory containing this script:
%   fMRISimulation/02_z0SensitivityAnalysis/
script_dir = fileparts(mfilename('fullpath'));

% Project root directory:
%   fMRISimulation/
project_root = fileparts(script_dir);

% Shared FWCCA functions:
%   fMRISimulation/Functions/
functions_dir = fullfile(project_root, 'Functions');

if ~exist(functions_dir, 'dir')
    error('Functions directory does not exist:\n%s', functions_dir);
end

% Add the project root so that the MATLAB package
%   fMRISimulation/+z0sensitivity/
% can be accessed as z0sensitivity.*
addpath(project_root);

% Add shared FWCCA functions
addpath(functions_dir);


%% ============================================================
% Input and output directories
%% ============================================================

% Canonical-angle summary results:
%   fMRISimulation/02_z0SensitivityAnalysis/Results/
results_dir = fullfile(script_dir, 'Results');

if ~exist(results_dir, 'dir')
    error('Results directory does not exist:\n%s', results_dir);
end

% Generated figures:
%   fMRISimulation/02_z0SensitivityAnalysis/Figures/
figures_dir = fullfile(script_dir, 'Figures');

if ~exist(figures_dir, 'dir')
    mkdir(figures_dir);
end


%% ============================================================
% Load oracle-referenced canonical-angle summary
%% ============================================================

input_file = fullfile( ...
    results_dir, ...
    'FWCCA_z0Sensitivity_oracleReferenced_angle_summary_all.mat');

if ~exist(input_file, 'file')
    error('Canonical-angle summary file does not exist:\n%s', input_file);
end

load(input_file, 'AngleComparisonTable');

fprintf('\n============================================================\n');
fprintf('Loaded canonical-angle summary from:\n%s\n', input_file);
fprintf('All generated figures will be saved to:\n%s\n', figures_dir);
fprintf('============================================================\n');


methodNames = {'G-FWCCA','LG-FWCCA','GL-FWCCA'};
methodFileNames = {'G_FWCCA','LG_FWCCA','GL_FWCCA'};

% Names stored in AngleComparisonTable.Comparison
comparisonNames = { ...
    'Oracle vs noisy oracle', ...
    'Oracle vs preliminary CCA', ...
    'Oracle vs random matched'};

% Short labels displayed in the legend
comparisonLabels = { ...
    'Noisy oracle', ...
    'Preliminary CCA', ...
    'Random matched'};

lineStyles = {'-','--',':'};
markers = {'o','s','^'};
colors = lines(numel(comparisonNames));

Kcomp = 2;

% Font settings
fs_axis   = 22;
fs_label  = 22;
fs_title  = 24;
fs_legend = 22;

%% ============================================================
% Choose angle summary metric
%% ============================================================

% Mean angle
%metricName = 'meanAngle';
%metricFileName = 'MeanAngle';

% 95th percentile angle
metricName = 'p95Angle';
metricFileName = 'P95Angle';

%% ============================================================
% Generate figures
%% ============================================================

for methodIdx = 1:numel(methodNames)

    for compIdx = 1:Kcomp

        outName = sprintf( ...
            'FigS_z0Sensitivity_oracleReferenced_%s_%s_direction%d', ...
            metricFileName, methodFileNames{methodIdx}, compIdx);

        fig = figure('Name',outName, ...
            'Units','inches', ...
            'Position',[1 1 4.2 3.5], ...
            'Color','w');

        hold on;

        plotHandles = gobjects(0);
        legendLabels = {};

        for cidx = 1:numel(comparisonNames)

            idx = strcmp(AngleComparisonTable.Method, methodNames{methodIdx}) & ...
                  AngleComparisonTable.Component == compIdx & ...
                  strcmp(AngleComparisonTable.Comparison, comparisonNames{cidx});

            Tsub = AngleComparisonTable(idx,:);
            Tsub = sortrows(Tsub,'SNR');

            if isempty(Tsub)
                fprintf('No data: %s, component %d, %s\n', ...
                    methodNames{methodIdx}, compIdx, comparisonNames{cidx});
                continue;
            end

            h = plot(Tsub.SNR, Tsub.(metricName), ...
                'LineStyle',lineStyles{cidx}, ...
                'Marker',markers{cidx}, ...
                'Color',colors(cidx,:), ...
                'LineWidth',2.8, ...
                'MarkerSize',8, ...
                'MarkerFaceColor','w');

            plotHandles(end+1) = h;
            legendLabels{end+1} = comparisonLabels{cidx};

        end

        xlabel('SNR (dB)', 'FontSize',fs_label);
        ylabel('Degrees', 'FontSize',fs_label);

       

        grid on;
        box on;

        set(gca, ...
            'FontSize',fs_axis, ...
            'LineWidth',1.5);


        xlim([-5 5]);
        xticks(-5:1:5);

        ax = gca;
        ax.Toolbar.Visible = 'off';

        set(fig,'PaperPositionMode','auto');

        save_figure_PDFformat(fig, figures_dir);

    end

end






%% ============================================================
% Standalone legend
%% ============================================================

legendFig = figure('Name','FigS_z0Sensitivity_Legend', ...
    'Units','inches', ...
    'Position',[1 1 10 1.0], ...
    'Color','w');

ax = axes(legendFig);
hold(ax,'on');

legendHandles = gobjects(numel(comparisonLabels),1);

for cidx = 1:numel(comparisonLabels)

    legendHandles(cidx) = plot(ax,nan,nan, ...
        'LineStyle',lineStyles{cidx}, ...
        'Marker',markers{cidx}, ...
        'Color',colors(cidx,:), ...
        'LineWidth',2.8, ...
        'MarkerSize',10, ...
        'MarkerFaceColor','w');

end

lgd = legend(ax,legendHandles,comparisonLabels, ...
    'Orientation','horizontal', ...
    'Location','north', ...
    'Interpreter','none', ...
    'FontSize',24);

lgd.Box = 'off';

axis(ax,'off');

save_figure_PDFformat(legendFig, figures_dir);
