%% ============================================================
% Illustrative simulation for manuscript and supplementary figures
%
% This script generates one representative simulation trial at
% SNR = 0 dB and produces the following figures.
%
% Main manuscript:
%
% Figure 3:
%   Ground-truth spatial masks g_1 and g_2 together with example
%   noisy and true temporal signals for the box-car and quadratic
%   regions.
%
% Figure 4:
%   Canonical spatial maps for CCA, G-FWCCA, LG-FWCCA, and
%   GL-FWCCA at SNR = 0 dB, using h = 3.4 for the local methods.
%
% Figure 5:
%   Effective temporal weights for G-FWCCA, LG-FWCCA, and
%   GL-FWCCA at SNR = 0 dB.
%
% Figure 8:
%   Estimated canonical maps for the first two components across
%   bandwidths h for LG-FWCCA in a representative simulation
%   trial at SNR = 0 dB.
%   Panels (a) and (b) correspond to \hat{s}_1 and \hat{s}_2.
%
% Supplementary material:
%
% Supplementary Figure 13:
%   Estimated canonical maps for the first two components across
%   bandwidths h for GL-FWCCA in a representative simulation
%   trial at SNR = 0 dB.
%   Panels (a) and (b) correspond to \hat{s}_1 and \hat{s}_2.
%
% Output
% ------
% All figures generated by this script are saved in:
%
%   illustrativeExampleFigures/
%
% Simulation setup:
%   Spatial grid:              20 x 20 voxels
%   Number of time points:     200
%   Number of components:      2
%   SNR:                       0 dB
%   Monte Carlo runs:          M = 1
%   Candidate bandwidths:
%       h = [0.5 1.0 1.8 2.8 3.4 3.8 4.2 4.6 5]
%
% Methods:
%   CCA
%   G-FWCCA
%   LG-FWCCA
%   GL-FWCCA
%
%% ============================================================
clear; clc; close all;
%% ============================================================
% Project directories
%% ============================================================

% Directory containing this script:
%   fMRISimulation/01_MainSimulation/
script_dir = fileparts(mfilename('fullpath'));

% Project root directory:
%   fMRISimulation/
project_root = fileparts(script_dir);

% Shared FWCCA functions:
%   fMRISimulation/Functions/
functions_dir = fullfile(project_root, 'Functions');

% Check that the functions directory exists
if ~exist(functions_dir, 'dir')
    error('Functions directory does not exist:\n%s', functions_dir);
end

% Add shared FWCCA functions to the MATLAB path
addpath(functions_dir);
%% ============================================================
%  output directory
%% ============================================================

output_dir = 'illustrativeExampleFigures';

if ~exist(output_dir,'dir')
       mkdir(output_dir);
end

%% ============================================================
% Configuration
%% ============================================================
% Number of Monte Carlo simulations per SNR
M = 1;
% SNR levels
SNR_dB_list = 0;
% Spatial grid and time dimension
grid_size = [20, 20];
num_voxels = prod(grid_size);
num_timepoints = 200;
% Number of canonical components
Kcomp = 2;
% Number of SNR settings
nSNR = numel(SNR_dB_list);
% Number of methods:
%   results:
%       1 = CCA
%       2 = G-FWCCA
%
%   LocalWeightVariantresults:
%       1 = LG-FWCCA
%       2 = GL-FWCCA
nMeth = 2;
% Candidate bandwidths
h_list = [0.5 1.0 1.8 2.8 3.4 3.8 4.2 4.6 5];
n_h = numel(h_list);

%% ============================================================
% Initialize result structures
%% ============================================================
% ------------------------------------------------------------
% LG-FWCCA / GL-FWCCA results
%
% Dimension:
% method × SNR × Monte Carlo run × bandwidth
% ------------------------------------------------------------
LocalWeightVariantresults =cell(nMeth, nSNR, M, n_h);
for midx = 1:nMeth

    for sidx = 1:nSNR

        for m = 1:M

            for h_idx = 1:n_h

                S = struct( ...
                    'LocalVals',    zeros(1, Kcomp), ...
                    'AvgLocalVals', zeros(1, 1), ...
                    'AUCs_Train',   zeros(1, 1), ...
                    'AUCs_Test',    zeros(1, 1), ...
                    'EV_Train',     zeros(1, Kcomp), ...
                    'RCOR_Train',   zeros(1, Kcomp), ...
                    'EV_Test',      zeros(1, Kcomp), ...
                    'RCOR_Test',    zeros(1, Kcomp), ...
                    'Comp1_Test',   zeros(num_voxels, Kcomp));

                LocalWeightVariantresults{ ...
                    midx, sidx, m, h_idx} = S;

            end
        end
    end
end

% ------------------------------------------------------------
% CCA / G-FWCCA results
%
% Dimension:
% method × SNR × Monte Carlo run
% ------------------------------------------------------------
results = cell(nMeth, nSNR, M);

for midx = 1:nMeth

    for sidx = 1:nSNR

        for m = 1:M

            results{midx,sidx,m} = struct( ...
                'LocalVals',    zeros(1, Kcomp), ...
                'AvgLocalVals', zeros(1, 1), ...
                'AUCs_Train',   zeros(1, 1), ...
                'AUCs_Test',    zeros(1, 1), ...
                'EV_Train',     zeros(1, Kcomp), ...
                'RCOR_Train',   zeros(1, Kcomp), ...
                'EV_Test',      zeros(1, Kcomp), ...
                'RCOR_Test',    zeros(1, Kcomp), ...
                'Comp1_Test',   cell(1,1));

        end
    end
end

%% ============================================================
% Generate canonical temporal signals
%% ============================================================

boxcar_signal = repmat([ones(1,10), zeros(1,10)], 1, num_timepoints/20);
boxcar_signal = (boxcar_signal - mean(boxcar_signal)) / std(boxcar_signal);
quadratic_trend = (linspace(-1,1,num_timepoints)).^2;
quadratic_trend = (quadratic_trend - mean(quadratic_trend)) / std(quadratic_trend);
centerB0 = [9, 9];    szB = [6, 6];
centerQ0 = [13, 13];  szQ = [3, 3];
jitRange = [-2 2; -2 2];

%% ============================================================
% Main simulation loop
%% ============================================================
svdTol   =1e-1;
ridgeTol =1e-4;

for sidx = 1:nSNR

    SNR_dB = SNR_dB_list(sidx);
    sigma_noise = sqrt(1 / (10^(SNR_dB/10)));

    for m = 1:M

        rng(100000 * sidx + m);

        %% ----------------------------------------------------
        % Generate Boxcar region
        %% ----------------------------------------------------

        dB = draw_jitter(jitRange);
        centerB = centerB0 + dB;
        [rowsB, colsB] = block_from_center(centerB, szB, grid_size);
        [RB, CB] = meshgrid(rowsB, colsB);
        boxcar_idx = sub2ind(grid_size, RB(:), CB(:));

        %% ----------------------------------------------------
        % Generate Quadratic region with overlap
        %% ----------------------------------------------------

        placed = false;

        while ~placed
            dQ = draw_jitter(jitRange);
            centerQ = centerQ0 + dQ;
            [rowsQ, colsQ] = block_from_center(centerQ, szQ, grid_size);
            [RQ, CQ] = meshgrid(rowsQ, colsQ);
            quadratic_idx = sub2ind(grid_size, RQ(:), CQ(:));

            if ~isempty(intersect(boxcar_idx, quadratic_idx))
                placed = true;
            end
        end

        %% ----------------------------------------------------
        % Generate clean signal and noisy train/test data
        %% ----------------------------------------------------

        Xsignal = zeros(num_timepoints, num_voxels);
        Xsignal(:, boxcar_idx) = Xsignal(:, boxcar_idx) + boxcar_signal';
        Xsignal(:, quadratic_idx) = Xsignal(:, quadratic_idx) + quadratic_trend';

        Xtrain = Xsignal + sigma_noise * randn(size(Xsignal));
        Xtest  = Xsignal + sigma_noise * randn(size(Xsignal));

        Ytrain = Construct4SpatialNeighborsfmri(Xtrain, grid_size);

        XTrain = Xtrain';
        YTrain = Ytrain';
        XTest  = Xtest';

        %% ----------------------------------------------------
        % Ground-truth activation labels
        %% ----------------------------------------------------

        n = size(XTrain,1);

        G = zeros(n,2);
        G(boxcar_idx,1) = 1;
        G(quadratic_idx,2) = 1;

        Z_true = sum(G,2) > 0;

        %% ----------------------------------------------------
        % Noisy pseudo-label initialization
        %% ----------------------------------------------------

        Z0 = Z_true;

        idx_fp = randsample(find(~Z0), round(0.2 * sum(~Z0)));
        idx_fn = randsample(find(Z0),  round(0.2 * sum(Z0)));

        Z0(idx_fp) = 1;
        Z0(idx_fn) = 0;

        %% ----------------------------------------------------
        % Initial global temporal weights
        %% ----------------------------------------------------

        Z0c = Z0 - mean(Z0);
        Xc = XTrain - mean(XTrain,1);

        corrs = abs((Xc' * Z0c) ./ sqrt(sum(Xc.^2,1)' * sum(Z0c.^2)));
        corrs(isnan(corrs)) = 0;

        w0 = num_timepoints * corrs / sum(corrs);
        Wg_0 = diag(w0);


        %% ====================================================
        % CCA
        %% ====================================================

        midx = 1;

        resCCA_T = Run_FWCCA_Family(XTrain, YTrain, ...
            eye(num_timepoints), eye(num_timepoints), ...
            eye(num_timepoints), eye(num_timepoints), ...
            Kcomp, 100, 1e-5, 'postScale',ridgeTol,svdTol);

        XtestCCA_locentered = XTest - repmat(resCCA_T.X1_localMean, n, 1);
        resCCA_E.comp1 = XtestCCA_locentered * resCCA_T.Ak_raw;

        results{midx,sidx,m}.Comp1_Test = resCCA_E.comp1;

        EV_CCAT = EV_from_projection_C(resCCA_T.comp1, G, 1e-5);
        EV_CCAE = EV_from_projection_C(resCCA_E.comp1, G, 1e-5);

        results{midx,sidx,m}.EV_Train   = EV_CCAT.EV;
        results{midx,sidx,m}.EV_Test    = EV_CCAE.EV;
        results{midx,sidx,m}.RCOR_Train = EV_CCAT.RCOR;
        results{midx,sidx,m}.RCOR_Test  = EV_CCAE.RCOR;

        combinedCCA_T_map = sum(abs(resCCA_T.comp1),2);
        combinedCCA_E_map = sum(abs(resCCA_E.comp1),2);

        results{midx,sidx,m}.AUCs_Train = computeAUC(combinedCCA_T_map, Z_true);
        results{midx,sidx,m}.AUCs_Test  = computeAUC(combinedCCA_E_map, Z_true);


        %% ====================================================
        % G-FWCCA
        %% ====================================================

        midx = 2;

        resG_T = Run_FWCCA_Family(XTrain, YTrain, ...
            Wg_0, Wg_0, eye(num_timepoints), eye(num_timepoints), ...
            Kcomp, 100, 1e-5, 'postScale', ridgeTol, svdTol);

        XtestG_locentered = XTest - repmat(resG_T.X1_localMean, n, 1);
        resG_E.comp1 = XtestG_locentered * resG_T.Ak_raw;

        results{midx,sidx,m}.Comp1_Test = resG_E.comp1;

        EV_GT = EV_from_projection_C(resG_T.comp1, G, 1e-5);
        EV_GE = EV_from_projection_C(resG_E.comp1, G, 1e-5);

        results{midx,sidx,m}.EV_Train   = EV_GT.EV;
        results{midx,sidx,m}.EV_Test    = EV_GE.EV;
        results{midx,sidx,m}.RCOR_Train = EV_GT.RCOR;
        results{midx,sidx,m}.RCOR_Test  = EV_GE.RCOR;

        combinedG_T_map = sum(abs(resG_T.comp1),2);
        combinedG_E_map = sum(abs(resG_E.comp1),2);

        results{midx,sidx,m}.AUCs_Train = computeAUC(combinedG_T_map, Z_true);
        results{midx,sidx,m}.AUCs_Test  = computeAUC(combinedG_E_map, Z_true);


        %% ----------------------------------------------------
        % Local spatial variance: CCA / G-FWCCA
        %% ----------------------------------------------------

        for k = 1:Kcomp
            map_CCA = reshape(resCCA_T.comp1(:,k), grid_size);
            map_G   = reshape(resG_T.comp1(:,k), grid_size);

            results{1,sidx,m}.LocalVals(k) = computeLocalVariance3x3(map_CCA);
            results{2,sidx,m}.LocalVals(k) = computeLocalVariance3x3(map_G);
        end

        for midx = 1:nMeth
            results{midx,sidx,m}.AvgLocalVals = mean(results{midx,sidx,m}.LocalVals);
        end


        %% ====================================================
        % LG-FWCCA / GL-FWCCA across bandwidths
        %% ====================================================

        for h_idx = 1:n_h

            h = h_list(h_idx);
            K = makeLocalKernel(num_timepoints, 5, 'gaussian', h);
            fprintf('Run %d, bandwidth h = %.2f for local feature weight variants\n', m, h);

            %% ------------------------------------------------
            % LG-FWCCA
            %% ------------------------------------------------

            midx = 1;

            resLG_T = Run_FWCCA_Family(XTrain, YTrain, ...
                Wg_0, Wg_0, K, K, ...
                Kcomp, 100, 1e-5, 'postScale',ridgeTol, svdTol);

            XtestLG_locentered = XTest - repmat(resLG_T.X1_localMean, n, 1);
            resLG_E.comp1 = XtestLG_locentered * resLG_T.Ak_raw;

            LocalWeightVariantresults{midx,sidx,m,h_idx}.Comp1_Test = resLG_E.comp1;

            EV_LGT = EV_from_projection_C(resLG_T.comp1, G, 1e-5);
            EV_LGE = EV_from_projection_C(resLG_E.comp1, G, 1e-5);

            LocalWeightVariantresults{midx,sidx,m,h_idx}.EV_Train   = EV_LGT.EV;
            LocalWeightVariantresults{midx,sidx,m,h_idx}.EV_Test    = EV_LGE.EV;
            LocalWeightVariantresults{midx,sidx,m,h_idx}.RCOR_Train = EV_LGT.RCOR;
            LocalWeightVariantresults{midx,sidx,m,h_idx}.RCOR_Test  = EV_LGE.RCOR;

            combinedLG_T_map = sum(abs(resLG_T.comp1),2);
            combinedLG_E_map = sum(abs(resLG_E.comp1),2);

            LocalWeightVariantresults{midx,sidx,m,h_idx}.AUCs_Train = computeAUC(combinedLG_T_map, Z_true);
            LocalWeightVariantresults{midx,sidx,m,h_idx}.AUCs_Test  = computeAUC(combinedLG_E_map, Z_true);


            %% ------------------------------------------------
            % GL-FWCCA
            %% ------------------------------------------------

            midx = 2;

            resGL_T = Run_FWCCA_Family(XTrain, YTrain, ...
                Wg_0, Wg_0, K, K, ...
                Kcomp, 100, 1e-5, 'preScale', ridgeTol, svdTol);

            XtestGL_locentered = XTest - repmat(resGL_T.X1_localMean, n, 1);
            resGL_E.comp1 = XtestGL_locentered * resGL_T.Ak_raw;

            LocalWeightVariantresults{midx,sidx,m,h_idx}.Comp1_Test = resGL_E.comp1;

            EV_GLT = EV_from_projection_C(resGL_T.comp1, G, 1e-5);
            EV_GLE = EV_from_projection_C(resGL_E.comp1, G, 1e-5);

            LocalWeightVariantresults{midx,sidx,m,h_idx}.EV_Train   = EV_GLT.EV;
            LocalWeightVariantresults{midx,sidx,m,h_idx}.EV_Test    = EV_GLE.EV;
            LocalWeightVariantresults{midx,sidx,m,h_idx}.RCOR_Train = EV_GLT.RCOR;
            LocalWeightVariantresults{midx,sidx,m,h_idx}.RCOR_Test  = EV_GLE.RCOR;

            combinedGL_T_map = sum(abs(resGL_T.comp1),2);
            combinedGL_E_map = sum(abs(resGL_E.comp1),2);

            LocalWeightVariantresults{midx,sidx,m,h_idx}.AUCs_Train = computeAUC(combinedGL_T_map, Z_true);
            LocalWeightVariantresults{midx,sidx,m,h_idx}.AUCs_Test  = computeAUC(combinedGL_E_map, Z_true);


            %% ------------------------------------------------
            % Local spatial variance: LG / GL
            %% ------------------------------------------------

            for k = 1:Kcomp
                map_LG = reshape(resLG_T.comp1(:,k), grid_size);
                map_GL = reshape(resGL_T.comp1(:,k), grid_size);

                LocalWeightVariantresults{1,sidx,m,h_idx}.LocalVals(k) = computeLocalVariance3x3(map_LG);
                LocalWeightVariantresults{2,sidx,m,h_idx}.LocalVals(k) = computeLocalVariance3x3(map_GL);
            end

            for midx = 1:nMeth
                LocalWeightVariantresults{midx,sidx,m,h_idx}.AvgLocalVals = ...
                    mean(LocalWeightVariantresults{midx,sidx,m,h_idx}.LocalVals);
            end

         end


    

            snrVal = SNR_dB_list(sidx);

            % font settings
            fs_axis  = 20;
            fs_label = 18;
            fs_title = 22;
        

            %% =================================================
            % Figure 3
            % Ground-truth masks and example time courses
            %% =================================================

            G_boxcar = reshape(G(:,1), grid_size);
            G_quadratic = reshape(G(:,2), grid_size);

            boxcar_only_idx = setdiff(boxcar_idx, quadratic_idx);
            quadratic_only_idx = setdiff(quadratic_idx, boxcar_idx);

            if isempty(boxcar_only_idx)
                example_boxcar_idx = boxcar_idx(1);
            else
                example_boxcar_idx = boxcar_only_idx(1);
            end

            if isempty(quadratic_only_idx)
                example_quadratic_idx = quadratic_idx(1);
            else
                example_quadratic_idx = quadratic_only_idx(1);
            end

            true_boxcar = Xsignal(:,example_boxcar_idx);
            noisy_boxcar = Xtrain(:,example_boxcar_idx);

            true_quadratic = Xsignal(:,example_quadratic_idx);
            noisy_quadratic = Xtrain(:,example_quadratic_idx);

            fig = figure('Name', sprintf('GroundTruthMasks_TimeCourses_SNR_%+ddB', SNR_dB), ...
                'Color','w','Units','inches','Position',[1 1 9.5 5.8]);

            ax1 = subplot(2,2,1);
            ax2 = subplot(2,2,2);
            ax3 = subplot(2,2,3);
            ax4 = subplot(2,2,4);

            set(ax1,'Position',[0.04 0.60 0.14 0.27]);
            set(ax2,'Position',[0.27 0.60 0.69 0.27]);
            set(ax3,'Position',[0.04 0.13 0.14 0.27]);
            set(ax4,'Position',[0.27 0.13 0.69 0.27]);

            % Boxcar mask
            imagesc(ax1,G_boxcar);
            axis(ax1,'image','off');
            caxis(ax1,[0 1]);
            colormap(ax1,gray(2));

            title(ax1,'$\mathbf{g}_1$: Boxcar', ...
                'Interpreter','latex','FontSize',fs_title);

            % Boxcar time course
            plot(ax2,1:num_timepoints,noisy_boxcar,'k-','LineWidth',1.2);
            hold(ax2,'on');
            plot(ax2,1:num_timepoints,true_boxcar,'r--','LineWidth',1.4);
            hold(ax2,'off');

            ylim(ax2,[-4 4]);
            box(ax2,'on');
            grid(ax2,'on');

            xlabel(ax2,'Time point','FontSize',fs_label);
            ylabel(ax2,'Signal','FontSize',fs_label);
            title(ax2,'Example Boxcar voxel time course','FontSize',fs_title);
            set(ax2,'FontSize',fs_axis,'LineWidth',1.0);

            % Quadratic mask
            imagesc(ax3,G_quadratic);
            axis(ax3,'image','off');
            caxis(ax3,[0 1]);
            colormap(ax3,gray(2));

            title(ax3,'$\mathbf{g}_2$: Quadratic', ...
                'Interpreter','latex','FontSize',fs_title);

            % Quadratic time course
            plot(ax4,1:num_timepoints,noisy_quadratic,'k-','LineWidth',1.2);
            hold(ax4,'on');
            plot(ax4,1:num_timepoints,true_quadratic,'r--','LineWidth',1.4);
            hold(ax4,'off');

            ylim(ax4,[-4 4]);
            box(ax4,'on');
            grid(ax4,'on');

            xlabel(ax4,'Time point','FontSize',fs_label);
            ylabel(ax4,'Signal','FontSize',fs_label);
            title(ax4,'Example Quadratic voxel time course','FontSize',fs_title);
            set(ax4,'FontSize',fs_axis,'LineWidth',1.0);

            save_figure_PDFformat(fig, output_dir);


            %% =================================================
            % Figure 4
            % Canonical maps for four methods
            %% =================================================
            % font settings
            fs_axis  = 22;
            fs_title = 20;
            fs_cb    = 22;

            h_plot = 3.4;
            K_plot = makeLocalKernel(num_timepoints, 5, 'gaussian', h_plot);

            resLG_plot = Run_FWCCA_Family(XTrain, YTrain, ...
                Wg_0, Wg_0, K_plot, K_plot, ...
                Kcomp, 100, 1e-5, 'postScale',ridgeTol, svdTol);

            resGL_plot = Run_FWCCA_Family(XTrain, YTrain, ...
                Wg_0, Wg_0, K_plot, K_plot, ...
                Kcomp, 100, 1e-5, 'preScale',ridgeTol, svdTol);

            method_names = {'CCA','G-FWCCA','LG-FWCCA','GL-FWCCA'};

            training_maps = {resCCA_T.comp1, resG_T.comp1, ...
                resLG_plot.comp1, resGL_plot.comp1};

            % Sign alignment for visualization
            for method_idx = 1:numel(training_maps)
                current_maps = training_maps{method_idx};

                for k = 1:Kcomp
                    r_sign = corr(current_maps(:,k), G(:,k));

                    if isfinite(r_sign) && r_sign < 0
                        current_maps(:,k) = -current_maps(:,k);
                    end
                end

                training_maps{method_idx} = current_maps;
            end

            % One figure for each component
            for k = 1:Kcomp

                component_values = [];

                for method_idx = 1:numel(training_maps)
                    component_values = [component_values; training_maps{method_idx}(:,k)];
                end

                common_limit = max(abs(component_values));

                if common_limit == 0 || ~isfinite(common_limit)
                    common_limit = 1;
                end

                fig = figure('Name', sprintf( ...
                    'TrainingCanonicalMap_Comp%d_FourMethods_SNR_%+ddB_h%.1f', ...
                    k, SNR_dB, h_plot), ...
                    'Color','w','Units','inches','Position',[1 1 8.0 2.8]);

                tl = tiledlayout(1,4,'TileSpacing','compact','Padding','compact');

                for method_idx = 1:4
                    ax = nexttile(tl);

                    map_to_plot = reshape(training_maps{method_idx}(:,k), grid_size);

                    imagesc(ax,map_to_plot);
                    axis(ax,'image','off');
                    caxis(ax,[-common_limit common_limit]);

                    title(ax,method_names{method_idx}, ...
                       'FontSize',fs_title,'FontWeight','normal');
                end

                colormap(fig,parula);

                cb = colorbar;
                cb.Layout.Tile = 'east';
                cb.Label.String = 'Canonical index';
                cb.Label.FontSize = fs_cb;
                cb.FontSize = fs_axis;

                save_figure_PDFformat(fig, output_dir);
            end


            %% =================================================
            % Figure 5
            % Effective temporal weights
            %% =================================================
            % font settings
            fs_axis  = 20;
            fs_label = 20;
            fs_title = 22;
            h_eff = 3.4;
            K_eff = makeLocalKernel(num_timepoints, 5, 'gaussian', h_eff);

            resLG_eff = Run_FWCCA_Family(XTrain, YTrain, ...
                Wg_0, Wg_0, K_eff, K_eff, ...
                Kcomp, 100, 1e-5, 'postScale', ridgeTol, svdTol);

            resGL_eff = Run_FWCCA_Family(XTrain, YTrain, ...
                Wg_0, Wg_0, K_eff, K_eff, ...
                Kcomp, 100, 1e-5, 'preScale',ridgeTol, svdTol);

            weight_method_name = {'G-FWCCA','LG-FWCCA','GL-FWCCA'};

            effectiveWeight_data = { ...
                resG_T.effectiveWeight, ...
                resLG_eff.effectiveWeight, ...
                resGL_eff.effectiveWeight};

            fig = figure('Name', sprintf( ...
                'Example_EffectiveWeights_SNR_%+ddB_h_%.1f', snrVal, h_eff), ...
                'Color','w','Units','inches','Position',[1 1 9 3.5]);

            tl = tiledlayout(1,3,'TileSpacing','compact','Padding','compact');

            for midx_plot = 1:3
                ax = nexttile(tl);
                weight = effectiveWeight_data{midx_plot};

                scatter(ax,1:length(weight),weight,12,'filled');

                ylim(ax,[0 1.5]);
                xlabel(ax,'Time point','FontSize',fs_label);
                ylabel(ax,'Effective weight','FontSize',fs_label);

                title(ax,weight_method_name{midx_plot}, ...
                    'FontSize',fs_title,'FontWeight','normal');

                grid(ax,'on');
                box(ax,'on');
                set(ax,'FontSize',fs_axis,'LineWidth',1.0);
            end

            save_figure_PDFformat(fig, output_dir);

         
            %% =================================================
            % Figure 8
            % LG-FWCCA / GL-FWCCA maps across bandwidths
            % 3 x 3 layout
            %% =================================================
            % font settings
            fs_axis  = 20;
            fs_label = 20;
            fs_title = 22;
            fs_cb    = 20;
            local_method_name = {'LG-FWCCA','GL-FWCCA'};

            for local_midx = 1:2

               for k = 1:Kcomp

                    method_name_safe = strrep(local_method_name{local_midx},'-','_');

                    fig = figure('Name', sprintf( ...
                   'Example_%s_TestCanonicalMap_Comp%d_AcrossBandwidths_SNR_%+ddB', ...
                    method_name_safe, k, snrVal), ...
                    'Color','w','Units','inches','Position',[1 1 9.5 3.3]);

                   tl = tiledlayout(2,5,'TileSpacing','compact','Padding','compact');

                 for h_idx = 1:n_h

                     ax = nexttile(tl);
                     result_struct = LocalWeightVariantresults{local_midx,sidx,m,h_idx};

                    if isempty(result_struct) || isempty(result_struct.Comp1_Test)
                     axis(ax,'off');
                     continue;
                    end

                    comp_map = reshape(result_struct.Comp1_Test(:,k),grid_size);

                    imagesc(ax,comp_map);
                    axis(ax,'image','off');
                    caxis(ax,[-common_limit common_limit]);

                    title(ax,sprintf('$h=%.1f$',h_list(h_idx)), ...
                   'Interpreter','latex','FontSize',fs_title);
                end

               colormap(fig,parula);
               cb = colorbar;
               cb.Layout.Tile = 'east';
               cb.Label.String = 'Canonical index';
               cb.Label.FontSize = fs_cb;
               cb.FontSize = fs_axis;

               save_figure_PDFformat(fig, output_dir);
              end
       

        end

    end

end
