% =========================================================================
% SecondViewSensitivity_LG_GLFWCCA_CV_for_SingleSubject.m
%
% Cross-validation analysis for LG-FWCCA and GL-FWCCA in the second-view
% sensitivity study using the OpenNeuro Emotional Music dataset (ds000171).
%
% This script uses the training inputs generated by
% SecondViewSensitivity_TrainingAnalysis_for_SingleSubject.m and performs
% K-fold cross-validation for LG-FWCCA and GL-FWCCA separately for the
% positive and negative second views and for each second-view threshold.
%
% The script is provided as a single-subject example using sub-mdd02 from
% the MDD group. The same procedure can be applied to other MDD or ND
% subjects by changing groupName and subj below.
%
% INPUTS
% ------
% 1. Training inputs generated by the preceding training script:
%
%    03_SecondViewSensitivityAnalysis/
%        SubjectResults/<group>/<subject>/
%            <subject>_SecondViewInputs.mat
%
%    This file contains AllTrainInputs, including X1, the threshold-specific
%    second views X2, the analysis mask, global feature weights Wg_0, TR,
%    and other training settings.
%
% 2. Preprocessed training fMRI:
%
%    Data/<group>/<subject>/func/
%        swar<subject>_task-music_trainrun_bold.nii
%
%    The image is supplied to CV_FWCCA_task for atlas-based evaluation.
%
% CROSS-VALIDATION SETTINGS
% -------------------------
% Cross-validation is performed separately for:
%
%    - positive and negative second views;
%    - six second-view thresholds: p90, p85, p80, p75, p70, and p65;
%    - cumulative canonical-component settings K = 1,...,Kcomp_max.
%
% Local-kernel hyperparameters are searched over:
%
%    h = 0.25:0.25:2
%    r = 1
%
% using 10-fold cross-validation.
%
% METHODS
% -------
% LG-FWCCA:
%    local weighting followed by global weighting
%    mixOrder = 'postscale'
%
% GL-FWCCA:
%    global weighting followed by local weighting
%    mixOrder = 'prescale'
%
% For each method, threshold, and value of K, the functional-system counts
% are accumulated over canonical components 1:K. The (h,r) combination
% giving the largest cumulative mean count is selected separately for each K.
%
% OUTPUT
% ------
% Results are saved to:
%
%    03_SecondViewSensitivityAnalysis/
%        SubjectResults/<group>/<subject>/
%            <subject>_LG_GLFWCCA_CVResults.mat
%
% The output structure LG_GLFWCCA_TrainingResults stores the raw and
% cumulative cross-validation counts, the K-specific selected (h,r)
% combinations, maximum cumulative counts, and summary tables for each
% second-view definition and threshold.
%
% IMPORTANT
% ---------
% All cross-validation and hyperparameter selection use the trainrun only.
% The independent testrun is not used at this stage.
%
% Example subject:
%    Group   : MDD
%    Subject : sub-mdd02
%    Run     : trainrun
% =========================================================================

clear;
close all;
clc;

%% ============================================================
% Project paths
% ============================================================

analysisRoot = fileparts(mfilename('fullpath'));
datasetRoot = fileparts(analysisRoot);
projectRoot = fileparts(datasetRoot);

spm_dir = fullfile(projectRoot, 'spm_25');
functions_dir = fullfile(datasetRoot, 'Functions');

if ~exist(spm_dir, 'dir')
    error('SPM directory does not exist:\n%s', spm_dir);
end

if ~exist(functions_dir, 'dir')
    error('Functions directory does not exist:\n%s', functions_dir);
end


%% ============================================================
% SPM and function setup
% ============================================================

addpath(spm_dir);
addpath(functions_dir);

spm('defaults', 'fmri');
spm_jobman('initcfg');

atlas = spm_atlas('load', 'Neuromorphometrics');


%% ============================================================
% Subject settings
%
% sub-mdd02 from the MDD group is used as an example.
% ============================================================

groupName = 'MDD';
subj = 'sub-mdd02';
currentrun = 'trainrun';

dataRoot = fullfile(datasetRoot, 'Data', groupName);
subjectResultsRoot = fullfile(analysisRoot, 'SubjectResults', groupName, subj);

if ~exist(subjectResultsRoot, 'dir')
    mkdir(subjectResultsRoot);
end


%% ============================================================
% Analysis settings
% ============================================================

viewTypeList = {'positive', 'negative'};
nViews = numel(viewTypeList);

Kcomp_max = 5;
h_list = 0.25:0.25:2;
r_list = 1;
nFold = 10;

percentile_list = [90 85 80 75 70 65];
nThresholds = numel(percentile_list);

svdTol = 1e-2;
ridgeTol = 1e-5;

fprintf('\n');
fprintf('============================================================\n');
fprintf('Second-view sensitivity: LG / GL-FWCCA cross-validation\n');
fprintf('============================================================\n');
fprintf('Group   : %s\n', groupName);
fprintf('Subject : %s\n', subj);
fprintf('Kmax    : %d\n', Kcomp_max);
fprintf('Folds   : %d\n', nFold);
fprintf('============================================================\n');


%% ============================================================
% Subject paths
% ============================================================

subj_dir = fullfile(dataRoot, subj);
func_dir = fullfile(subj_dir, 'func');


%% ============================================================
% Load training functional image
%
% Used by CV_FWCCA_task for atlas-based evaluation.
% ============================================================

functional_pattern = ['^swar' subj '_task-music_' currentrun '_bold\.nii$'];
files = spm_select('FPList', func_dir, functional_pattern);

if isempty(files)
    error('Cannot find preprocessed fMRI for %s.', subj);
end

if size(files, 1) > 1
    error('More than one training functional image was found for %s.', subj);
end

nii_path = strtrim(files(1,:));

fprintf('\nFunctional image:\n%s\n', nii_path);


%% ============================================================
% Load saved second-view inputs
% ============================================================

inputFile = fullfile(subjectResultsRoot, sprintf('%s_SecondViewInputs.mat', subj));

if ~exist(inputFile, 'file')
    error('Cannot find second-view inputs for %s:\n%s', subj, inputFile);
end

fprintf('\nLoading second-view inputs:\n%s\n', inputFile);

S = load(inputFile, 'AllTrainInputs');

if ~isfield(S, 'AllTrainInputs')
    error('AllTrainInputs is not found in:\n%s', inputFile);
end

AllTrainInputs = S.AllTrainInputs;
clear S;


%% ============================================================
% Basic input checks
% ============================================================

if numel(AllTrainInputs) ~= nViews
    error('Expected %d second-view types, but AllTrainInputs contains %d.', ...
        nViews, numel(AllTrainInputs));
end


%% ============================================================
% Training information common to all views / thresholds
% ============================================================

X1Mask = AllTrainInputs{1}.X1Mask;
idx_mask = AllTrainInputs{1}.idx_mask;
final_mask = AllTrainInputs{1}.final_mask;
Wg_0 = AllTrainInputs{1}.Wg_0;
TR = AllTrainInputs{1}.TR;

vol_size_3d = size(final_mask);


%% ============================================================
% Check analysis settings stored with the input
% ============================================================

if isfield(AllTrainInputs{1}, 'Kcomp_max') && ...
        AllTrainInputs{1}.Kcomp_max ~= Kcomp_max

    error('Kcomp_max mismatch: script uses %d, but input stores %d.', ...
        Kcomp_max, AllTrainInputs{1}.Kcomp_max);
end


%% ============================================================
% Result container
% ============================================================

LG_GLFWCCA_TrainingResults = struct([]);


%% ============================================================
% Loop over positive / negative second views
% ============================================================

for viewIdx = 1:nViews

    viewType = viewTypeList{viewIdx};
    trainInput = AllTrainInputs{viewIdx};

    fprintf('\n');
    fprintf('============================================================\n');
    fprintf('View = %s\n', viewType);
    fprintf('============================================================\n');


    %% --------------------------------------------------------
    % Check view identity
    %% --------------------------------------------------------

    if isfield(trainInput, 'viewType') && ~strcmpi(trainInput.viewType, viewType)
        error('View mismatch at index %d: expected %s, but input stores %s.', ...
            viewIdx, viewType, trainInput.viewType);
    end


    %% --------------------------------------------------------
    % Check second-view thresholds
    %% --------------------------------------------------------

    if ~isfield(trainInput, 'secondViewThresholds')
        error('secondViewThresholds is missing for view %s.', viewType);
    end

    if numel(trainInput.secondViewThresholds) ~= nThresholds
        error('Expected %d thresholds for view %s, but found %d.', ...
            nThresholds, viewType, numel(trainInput.secondViewThresholds));
    end


    %% --------------------------------------------------------
    % Store view-level information
    %% --------------------------------------------------------

    LG_GLFWCCA_TrainingResults(viewIdx).subject = subj;
    LG_GLFWCCA_TrainingResults(viewIdx).viewType = viewType;
    LG_GLFWCCA_TrainingResults(viewIdx).Kcomp_max = Kcomp_max;
    LG_GLFWCCA_TrainingResults(viewIdx).h_list = h_list;
    LG_GLFWCCA_TrainingResults(viewIdx).r_list = r_list;
    LG_GLFWCCA_TrainingResults(viewIdx).nFold = nFold;


    %% ========================================================
    % Loop over second-view thresholds
    % ========================================================

    for id_p = 1:nThresholds

        percentileValue = percentile_list(id_p);
        topProportion = 100 - percentileValue;

        fprintf('\n');
        fprintf('------------------------------------------------------------\n');
        fprintf('%s | percentile = %d | top = %d%%\n', ...
            viewType, percentileValue, topProportion);
        fprintf('------------------------------------------------------------\n');


        %% ----------------------------------------------------
        % Check threshold identity
        %% ----------------------------------------------------

        storedPercentile = trainInput.secondViewThresholds(id_p).percentile;

        if storedPercentile ~= percentileValue
            error(['Percentile mismatch for view %s at threshold %d: ' ...
                'expected %g, stored %g.'], ...
                viewType, id_p, percentileValue, storedPercentile);
        end


        %% ----------------------------------------------------
        % Retrieve second view
        %% ----------------------------------------------------

        X2Mask = trainInput.secondViewThresholds(id_p).X2Mask;

        if isempty(X2Mask)
            error('X2Mask is empty for view %s at threshold %d.', viewType, id_p);
        end

        if ~isequal(size(X2Mask), size(X1Mask))
            error('X1Mask and X2Mask have inconsistent sizes for view %s at threshold %d.', ...
                viewType, id_p);
        end


        %% ====================================================
        % LG-FWCCA cross-validation
        %
        % Local weighting -> global weighting
        % mixOrder = 'postscale'
        % ====================================================

        fprintf('\nRunning LG-FWCCA cross-validation...\n');

        [~, LG_mean_count] = CV_FWCCA_task( ...
            idx_mask, X1Mask, X2Mask, vol_size_3d, atlas, nii_path, ...
            Wg_0, Kcomp_max, h_list, r_list, nFold, TR, ...
            'postscale', ridgeTol, svdTol);


        %% ====================================================
        % GL-FWCCA cross-validation
        %
        % Global weighting -> local weighting
        % mixOrder = 'prescale'
        % ====================================================

        fprintf('\nRunning GL-FWCCA cross-validation...\n');

        [~, GL_mean_count] = CV_FWCCA_task( ...
            idx_mask, X1Mask, X2Mask, vol_size_3d, atlas, nii_path, ...
            Wg_0, Kcomp_max, h_list, r_list, nFold, TR, ...
            'prescale', ridgeTol, svdTol);


        %% ====================================================
        % Cumulative functional-system counts
        %
        % Dimension 3 corresponds to canonical components.
        % Slice K therefore represents components 1:K.
        % ====================================================

        LG_cum_mean_count = cumsum(LG_mean_count, 3);
        GL_cum_mean_count = cumsum(GL_mean_count, 3);


        %% ====================================================
        % Select best (h,r) separately for each cumulative K
        % ====================================================

        LG_best_hAndr = nan(Kcomp_max, 2);
        GL_best_hAndr = nan(Kcomp_max, 2);

        LG_maxCumCount = nan(Kcomp_max, 1);
        GL_maxCumCount = nan(Kcomp_max, 1);

        for k = 1:Kcomp_max

            % LG-FWCCA
            current_LG = LG_cum_mean_count(:,:,k);
            [LG_maxCumCount(k), linear_idx] = max(current_LG, [], 'all', 'linear');
            [best_h_idx, best_r_idx] = ind2sub(size(current_LG), linear_idx);
            LG_best_hAndr(k,:) = [h_list(best_h_idx), r_list(best_r_idx)];

            % GL-FWCCA
            current_GL = GL_cum_mean_count(:,:,k);
            [GL_maxCumCount(k), linear_idx] = max(current_GL, [], 'all', 'linear');
            [best_h_idx, best_r_idx] = ind2sub(size(current_GL), linear_idx);
            GL_best_hAndr(k,:) = [h_list(best_h_idx), r_list(best_r_idx)];

        end


        %% ====================================================
        % Summary tables
        % ====================================================

        K = (1:Kcomp_max)';

        LG_table = table(K, LG_best_hAndr(:,1), LG_best_hAndr(:,2), ...
            LG_maxCumCount, ...
            'VariableNames', {'K', 'Best_h', 'Best_r', 'MaxCumulativeCount'});

        GL_table = table(K, GL_best_hAndr(:,1), GL_best_hAndr(:,2), ...
            GL_maxCumCount, ...
            'VariableNames', {'K', 'Best_h', 'Best_r', 'MaxCumulativeCount'});

        fprintf('\nLG-FWCCA\n');
        disp(LG_table);

        fprintf('\nGL-FWCCA\n');
        disp(GL_table);


        %% ====================================================
        % Store threshold-level results
        % ====================================================

        R = struct();

        R.percentile = percentileValue;
        R.topProportion = topProportion;

        R.LG_mean_count = LG_mean_count;
        R.GL_mean_count = GL_mean_count;

        R.LG_cum_mean_count = LG_cum_mean_count;
        R.GL_cum_mean_count = GL_cum_mean_count;

        R.LG_best_hAndr = LG_best_hAndr;
        R.GL_best_hAndr = GL_best_hAndr;

        R.LG_maxCumCount = LG_maxCumCount;
        R.GL_maxCumCount = GL_maxCumCount;

        R.LG_table = LG_table;
        R.GL_table = GL_table;

        LG_GLFWCCA_TrainingResults(viewIdx).thresholdResults(id_p) = R;

    end

end


%% ============================================================
% Save LG / GL-FWCCA cross-validation results
% ============================================================

outputFile = fullfile(subjectResultsRoot, ...
    sprintf('%s_LG_GLFWCCA_CVResults.mat', subj));

fprintf('\n');
fprintf('============================================================\n');
fprintf('Saving LG / GL-FWCCA cross-validation results\n');
fprintf('============================================================\n');
fprintf('%s\n', outputFile);

save(outputFile, 'LG_GLFWCCA_TrainingResults', '-v7.3');

fprintf('\nSaved successfully.\n');
fprintf('============================================================\n');

